const languageList = [
    {
        id:1,
        lang:'Hindi',
        src:'./resources/images/lang/hindi.jpeg'
    },
    {
        id:2,
        lang:'English',
        src:'./resources/images/lang/english.jpeg'
    },
    {
        id:3,
        lang:'Telugu',
        src:'./resources/images/lang/telugu.jpeg'
    },
    {
        id:4,
        lang:'Tamil',
        src:'./resources/images/lang/tamil.jpeg'
    },
    {
        id:5,
        lang:'Malyalam',
        src:'./resources/images/lang/malyalam.jpeg'
    },
    {
        id:6,
        lang:'Kannada',
        src:'./resources/images/lang/kannada.jpeg'
    },
    {
        id:7,
        lang:'Marathi',
        src:'./resources/images/lang/marathi.jpeg'
    },
    {
        id:8,
        lang:'Punjabi',
        src:'./resources/images/lang/punjabi.jpeg'
    },
    {
        id:9,
        lang:'Bengali',
        src:'./resources/images/lang/bengali.jpeg'
    },
    {
        id:10,
        lang:'Gujarati',
        src:'./resources/images/lang/gujarati.jpeg'
    },
]
export default languageList