const movieGenre = [
    {
        id:1,
        genre:'Action',
        src:'./resources/images/genre/ActionMovie.jpg'
    },
    {
        id:2,
        genre:'Comedy',
        src:'./resources/images/genre/ComedyMovie.jpeg'
    },
    {
        id:3,
        genre:'Drama',
        src:'./resources/images/genre/DramaMovie.jpeg'
    },
    {
        id:4,
        genre:'Crime',
        src:'./resources/images/genre/CrimeMovie.jpeg'
    },
    {
        id:5,
        genre:'Animated',
        src:'./resources/images/genre/AnimatedMovie.jpg'
    },
    {
        id:6,
        genre:'Romance',
        src:'./resources/images/genre/RomanceMovie.jpg'
    },
    {
        id:7,
        genre:'Horror',
        src:'./resources/images/genre/HorrorMovie.jpeg'
    }
]
export default movieGenre